# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Antora Site
      # You may pin to the exact commit or the version.
      # uses: kameshsampath/antora-site-action@0c41c27fdd22b6cb711e8e5d8dfc09d359e81dfc
        uses: kameshsampath/antora-site-action@v0.2.3
        with:
          # The Antora playbook file
          antora_playbook: # default is site.yaml
          # The path relative to workspace root, where the asciidoc sources exits
          site_sources_path: # optional
