name: Antora Test Site 

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
env:
  SITE_DIR: '.'
jobs:
  build_site:
    name: "Build site with Antora"
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Generate site using antora site action"
        uses: kameshsampath/antora-site-action@master
        with:
          antora_playbook: antora-playbook.yml
      - name: "List folder"
        run: |
          ls -ltr $GITHUB_WORKSPACE/build/
      - name: "Upload generated site"
        uses: actions/upload-artifact@v1.0.0
        with:
          name: site
          path: "${{ github.workspace }}/build/${{ env.SITE_DIR }}"
